# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET http://localhost:5176/contracts
###

GET http://localhost:5176/testing/drives

###
GET http://localhost:5176/testing/download

###
POST http://localhost:5176/testing/folder?folderName=prueba3
###

GET http://localhost:5176/contracts/1

###
POST http://localhost:5176/contracts/tenant
Content-Type: application/json

{
  "id": "165",
  "version": "A",
  "flat": "1811",
  "complex": "Mazzaro",
  "utilityRoom": "160",
  "garage": "160",
  "address": "Cr 55 35-75",
  "price": "$1.500.000",
  "insurance": "$150.000",
  "duration": "12 Meses",
  "startDate": "16 de mayo de 2024",
  "endDate": "15 de mayo de 2025",
  "tenantName": "Juan Perez",
  "tenantId": "C.C. 123456789",
  "tenantPhone": "3001234567",
  "tenantEmail": "juanperez@prueba.com",
  "codebtorName": "Maria Perez",
  "codebtorId": "C.C. 987654321",
  "codebtorPhone": "3007654321",
  "codebtorEmail": "mariaperez@prueba.com",
  "payDay": "15"
  }

  ###
POST http://localhost:5176/contracts/tenant
Content-Type: application/json

{
  "id": "162",
  "version": "A",
  "flat": "1503",
  "complex": "CANARIAS",
  "utilityRoom": "106",
  "garage": "106",
  "address": "CR 44 N 62 S-33",
  "price": "$2.400.000",
  "insurance": "N/A (SURA)",
  "duration": "12 MESES 15 DIAS",
  "startDate": "1 de julio de 2024",
  "endDate": "14 de julio de 2025",
  "tenantName": "RUBEN DARIO LAZARO SOTO",
  "tenantId": "C.C. 1.152.216.866",
  "tenantPhone": "3104791009",
  "tenantEmail": "dariolazaro@gmail.com",
  "codebtorName": "JIMMY ANDRES VILLADA PEREZ",
  "codebtorId": "C.C. 1.088.334.253",
  "codebtorPhone": "3017887454",
  "codebtorEmail": "jimmyviipe@gmail.com",
  "payDay": "15"
  }